/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:PLACEHOLDER",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yDzCwJzig",
    "aws_user_pools_web_client_id": "7bjc5e1mtkeg5fbtbekhu1u4gr",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://PLACEHOLDER.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "CrowdsourcingApi",
            "endpoint": "https://llz2lc3n4j.execute-api.us-east-1.amazonaws.com/prod/",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
